[phases.setup]
nixPkgs = ["python3", "pkg-config", "gcc"]

[phases.install]
cmds = [
  "npm ci",
  "cd ../frontend && npm install"
]

[phases.build]
cmds = [
  "cd ../frontend && npm run build"
]

[variables]
NODE_VERSION = "20"
NODE_ENV = "production"

[start]
cmd = "node seed.js && node server.js"
